apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:Lww0puUD0nItjt/K5XBmpZUKShSdBYAkrr6IAtYJuLWG3eI7Iy4jgqWAJ6KdmWkhXtigCGwyJLfgAUMWpKHDj1wxZbKeZbGsKrcpJZn6OrPkKd+ZmAi/8jsNglKi5ihr4d8fN8wJGIyAGf0pB7OFNSwOt/pybdbe/VtTcbvi7hXFe4EnxxoI4DnK7tA3TxipEagQGvZYHM6Y+8yEWzNqxjvJ6pJtA+DJqwD86vG5kTJJa/Ju5NkQQgaUe234TEC9SKyBxdRDYLKgf1shlDBzRVKCugMesm9eQtF+Ww3iFJBuwvBkhnktBMv7GbI=,iv:06J0JWt6AzALHIWi0Ws3wotBG2YqQe5pouCaUeSzBY8=,tag:S/NlovcVrWE2sV+96gkHNw==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxdk9nRVlRVTRqRlpvQ095
            UDg1VzIyOFcyM3VOdHFrcTFFQWwyS0lmN25FCm0rMHpKTHUzTjFjeEhMVzJLZHNL
            TVEzMTlZSGNGUnJEanU4SzJsNjlTK28KLS0tIGIwM0ZiRm5MNnpwSzZza2lBY2dj
            ZnROcW00MnJLMWlaME9wUzFFTndBTUUKNcVAZ7gJcTY54nr5bGXYdjg5gXHchQS7
            B1ZCQ5j/S4BKDP9UvKQmsGGJkGI1XiNCWAkzb/dz7NkD7sUYAHgOVw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19ah6j55kkkecmcjakhjnj7xel0p8s9qegzphghj45jp7n20lqpnsrzw2gp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-19T14:37:32Z"
    mac: ENC[AES256_GCM,data:9gOLzLwo1g5j0VH3dhK9M19MifQNJ07KaO7sx4PX58mDXvWD/dI7LERmcTL5NsYCMBFZst4HAaaBJpD6pRiFmvhEgBH4T+KYCWwzEvbypPcsavtJnoETueQGXQ/gJl0XZr9Vswg0U2TvjyOD4UQ9NPhCa1HHlxj810/O8X5lQpE=,iv:QFgNtNxAvz8H5Zw2rH06qcio/HO0nHwA0MNBT5h5vTU=,tag:KTT9//CS5idcvba4ExeklA==,type:str]
    version: 3.13.0
