apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:KaUTzF1qn4PJ1fu10wMeTA6dR9dEMjHOmjkVulsBq2CYy96lmxTskPZwprEPHBXC+RD+VXK62NqjSfSmimXCcWOt4tX3pFFEcBhiQaUhRinFFtVBHM5v6tEcweaLG/bNo/Qr6OPldaFbbewhiEdySv24uT9XP84mNZjYsXmwsP75oh3JAhCn31IuIhaaF7tmudKaJYAFUfTj6aa2KW4Un8mWAWIhcwrolQDNbNuJgJ6KYO8/b6ZitWHFw6ilTYl99YkEhaP7nFaBfhLFu0/tGppqEXgAaqGNWsmhlMkWq+BiOdLDBqTyy1+bzJM=,iv:kT1qL0WL8zwCvCIIf61OW4VKBNqReREF8K1gV8QQ5WE=,tag:LHEPmrU7vGewANx2YsOuSA==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5dDlMZDJxQ3hCOUlSV24v
            WHJGOU5uSUhLMlZOcTA4eER5dEp4d0hTd0JRClZmMjFWWitpb0c3T0cwUkMrWll4
            TVp4RUt5L1VuWW4zQ3BkcytxTlJwR3MKLS0tIGNvc1VWMnFqc0M2aDZpeHg5YVRH
            SVcwRFNkMjhtOHh2UVp4cWw2OXpNdFUKzIGgiTLQvvXJLd5TSUgXjO1aTPHMBKse
            6RHPJ/towqXbmNNz55UmnPfAXUxZbjvBBXSBsPtkI9ul7a6jm3ycAg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19ah6j55kkkecmcjakhjnj7xel0p8s9qegzphghj45jp7n20lqpnsrzw2gp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-14T13:10:59Z"
    mac: ENC[AES256_GCM,data:3fzimWy1ok2l9Q+KHxVtPUdW0YgXOQ2/WLTgtSs+nfG1CZugjcvRPOeHyph365JWhxUs9F71MZIVywAdZVRCIL5pucE+llTNDF/iDQEuhzdh89Cl2y7Dz8evuxbG6W//SNOc2goY4c7MA/mKU465Vh0f7qbiDO0vb/MRk/ctIL8=,iv:rVhUZWenNsxVvB2+MHKDW8WxlxHAnw91qveu3+1gQjI=,tag:WPxxlnKuftKZoqIK1ul3Xw==,type:str]
    version: 3.13.0
