apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:V+XLbIowWtw=,iv:wgRDgt6V1hCgN5KiPskwEnQrIaKDIMJSIRXoAtZfabI=,tag:DeRFzwYNqUZozhMAzk1wVA==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:DsPNOZbqxHCaj/gS,iv:BzM3iccGZmEAC3yJdQEsNl61lPnYPP2FG1ws9Ibzj6s=,tag:uyqO8ggaKVyi1s6iZsIqKQ==,type:str]
kind: Secret
metadata:
    name: linkding-container-env
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsM0FJdTRML05nZ0Z6bUg2
            dFZwK0d5QTZwUW1SYVd0c2liOHVlQis1RVdzCmczRHdMRlN3eTVQNEFsTUhpRHBX
            REp3MzhiQWkvVXRVUktxdWlPeEhKR0kKLS0tIGFxd2lMeTV0Z0pGVWtRU1F2RWIz
            blFtbVBzbWcxOWVuenBEeEFNNHV4SU0K5ctB1d4u6ztwXTxH2Dqm/OQHQ7K/6w9/
            sS8KXHNJjCMo5ovodlP38gQoIIvW5AH3nmGFaoCDMQXayWAhsmr3VA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19ah6j55kkkecmcjakhjnj7xel0p8s9qegzphghj45jp7n20lqpnsrzw2gp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-14T13:17:25Z"
    mac: ENC[AES256_GCM,data:xLPqvEmWDTetUGsHD2PaF+3UapWCgnOOBcH8HdZLQBc7Erl2FKGTTsj34z7Vnk4jC8HA/7MbV0sOz3GpavK/IuNyNlCVacbizEY8mDx3dZHLq3g/Ht9uh06Pay4nmlZr1QQvim2L4O+/z8AWDGOQ55AnaFONWk8lgGaATa4Hx7s=,iv:Ou5QA/6HYgqhZ3u02kv7Ac1E0Fd25EDQ0jXa4pStHcs=,tag:eSpIFzQgNICDOgafAcPk5Q==,type:str]
    version: 3.13.0
