apiVersion: v1
data:
    password: ENC[AES256_GCM,data:O0iRAVxdzmN8U3D/,iv:dr8uNVBJeNyctWwoZafkyfbA3NojW/HYITVHsXgMc4k=,tag:qseTV2ekZ78ofHcN+LTLdg==,type:str]
    user: ENC[AES256_GCM,data:JcQrj2zDFeY=,iv:+THFQZ6g7MxY1cCH9Ccconc/3ObvcAbqw4drVseRaag=,tag:inNucaUtiExWr0cmW67IIA==,type:str]
kind: Secret
metadata:
    name: test-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXZGhBdnEwZm1STXFyZmRD
            Q0tIcnVrcVFqUHJXTkpkU1Jjdi9ScnBOekNnCkd3SGpldjFUZFRERmVTSlRBblBp
            d05Sd2lpZXI2U1YxdXJ0UW4weDhaaGMKLS0tIEdMODBKYVNkcDg4azhWVXQvbVdH
            OUh1eE1GdE5mSXV0bnZoYjB3RlhHZ3MKcb7Vw7UhsJAWyhnEFJSAvcXPdD8Yg1uI
            uOc0brwE78VxWlt/eUQlqczzNbShIsacSxClBukIviuqzKIfwZcv/w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19ah6j55kkkecmcjakhjnj7xel0p8s9qegzphghj45jp7n20lqpnsrzw2gp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-14T12:05:33Z"
    mac: ENC[AES256_GCM,data:tEg6i5RTH1l31aa3+ypzUdN/tebd98eqkWrbsmr12ooxVA/LiAO4c2vMsUIob+ks5VH8FInHJAuWu4bywrkW8pnvssKgn1dMDIY3yPoc3k+9X2i5+iknrUHvLzzB94p1QkPn7TcjIHRruvukDl/84bDgM4VouQoecRenXOfxDEA=,iv:Pfqslu+0tqfFHb/ZHoBekRBhqYS9ADsbcAAnOyJUOTc=,tag:htktsGPzU9GDXb3+cNviog==,type:str]
    version: 3.13.0
